version: '2'
services:
  db:
    image: postgres:13
    user: root
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: always             # run as a service
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  odoo14:
    image: ciperic/odoo-debug:14
    user: root
    depends_on:
      - db
    ports:
      - "11014:8069"
      - "21014:8072" # live chat
      - "5678:5678"  # python debug
    tty: true
    command: --
#    command: odoo scaffold /mnt/extra-addons/custom_module
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      # - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - ./addons:/mnt/addons
      #- ./enterprise:/mnt/enterprise
      - ./logs:/mnt/logs
      - ./etc:/etc/odoo
    restart: always             # run as a service
    
